# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    flickr.manager:
        class: AppBundle\Service\FlickrManager
        arguments: ['%flickr_api_key%', '%flickr_api_secret%']
